#!/bin/bash

# TODO if the property does not already exits, create it
#   xfconf-query -c xfce4-power-manager --create --type bool -p /xfce4-power-manager/presentation-mode -s true

function presentationmode() {
    if  [ "$1" = "true" ] ; then
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s true
        notify-send -i gnome-power-manager "Presentation mode is on"
    elif [ "$1" = "false" ] ; then
        xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s false
        notify-send -i gnome-power-manager "Presentation mode is off"
    else
        echo "unknown value. possibilities: 'true' 'false'"
    fi;
}

presentationmode "$1"
