#!/bin/bash

#find $1/.* -maxdepth 1 -type d -exec chmod 700 {} \; -exec setfacl -Rb {} +
#find $1/.* -maxdepth 1 -type f -exec chmod 600 {} \; -exec setfacl -Rb {} +

#find "$1/".* -maxdepth 1 -type f -exec echo  {} \; -exec echo "\n" {}  +

echo "done."
