#!/bin/bash

#
#   NetworkManager seems to keep interface still sleeping after system resume
#   from suspend to ram/disk. Restarting the service may help and this will
#   restart it automatically.
#

# service location
DIR="/var/lib/NetworkManager/"
FOUT0="/var/lib/NetworkManager/*.lease"
FOUT1="/var/lib/NetworkManager/timestamps"
FOUT2="/var/lib/NetworkManager/seen-bssids"
FOUT3="/var/lib/NetworkManager/secret_key"

#TODO

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# check if exists
if [ -f "$OUTPUT" ] ; then
    echo "'$OUTPUT' exists. Remove it and re-run this."
    exit 1
fi

# write it
cat << EOF > $OUTPUT
[Unit]
Description=Restart NetworkManager after resume
After=suspend.target

[Service]
Type=simple
ExecStart=/usr/bin/systemctl restart NetworkManager.service

[Install]
WantedBy=suspend.target
EOF

# enable&start it
systemctl enable resume-networkmanager.service
systemctl start resume-networkmanager.service

# done
echo "Done."

