#!/bin/bash
ACCEL="/sys/bus/iio/devices/iio:device0"



function readaccel() {
    #while true; do 
    ACCELLX=$(cat "$1/in_accel_x_raw")
    ACCELLY=$(cat "$1/in_accel_y_raw")
    ACCELLZ=$(cat "$1/in_accel_z_raw")
        #sleep "$2"
    #done
}


#readaccel "$ACCEL" "1" &


while true; do 
    readaccel "$ACCEL"
    echo $ACCELLX $ACCELLY $ACCELLZ
    sleep "1"
done

wait
