#!/bin/bash


function findall {
    find "$1" \
    -name '*.JPG' -o \
    -name '*.jpg' -o \
    -name '*.JEPG' -o \
    -name '*.jpeg' \
    | sort -h
}



A4="2480x3508"
A4_CELL="753x531"
#A4_CELL="531x753"
#-density 300 -units PixelsPerInch

SRCDIR=$1
OUTFILE=$2

mkdir -p $(dirname $OUTFILE)

montage -verbose -label '%t' -font Helvetica -pointsize 10 \
    -density 300 -units PixelsPerInch \
    -background '#ffffff' -fill 'black' \
    -define jpeg:size=200x200x \
    -geometry 527x812+15+15  -tile 5x2 \
    $(findall $SRCDIR) $OUTFILE


# contactsheet2 Hs "CS/CSH.jpg"; contactsheet-vert Vs "CS/CSV.jpg"

