#!/bin/bash


function findall {
    find "$1" \
    -maxdepth 1 \
    -name '*.JPG' -o \
    -name '*.jpg' -o \
    -name '*.JEPG' -o \
    -name '*.jpeg' \
    | sort -h
}

function smally {
    ORINT=$(identify $1 | cut -d' ' -f 3)
    larg=$(echo $ORINT | cut -d'x' -f 1)
    alt=$(echo $ORINT | cut -d'x' -f 2)

    if (( larg > alt )); then
        #echo $1 "horizont"  $larg vs $alt
        mv $1 $2/$(basename $1)
    else
        mv $1 $3/$(basename $1)
    fi
}
export -f smally

SRCDIR=$1
#OUTDIR=$2

HS="Hs"
VS="Vs"

mkdir -p $HS
mkdir -p $VS

#mkdir -p $OUTDIR
#cp -rn $SRCDIR/* $OUTDIR/
#SRCDIR=$OUTDIR

#if out'ed ir, then cp
#parallel -j 4 convert -quality 0% -strip -resize 2048x2048 {} {} ::: $(findall $OUTDIR)

parallel -j 6 smally {} $HS $VS ::: $(findall $SRCDIR)
