#!/bin/bash

ROOT="$(pscripts root)/sysadmin/archwa/diff"

DIFF="$ROOT/$1.sha256"
PATCH="$ROOT/$1.patch"

if [ ! -f "$DIFF" ]; then
    echo "No hash file found: '$DIFF'"
    exit 1
fi
if [ ! -f "$PATCH" ]; then
    echo "No patch file found: '$PATCH'"
    exit 1
fi

# check for sha256
res=$(sha256sum -c "$DIFF" 2>/dev/null | grep OK)

# patch
